nome = input('Nome completo: ')
print(f'Nome com letras maiúsculas: {nome.upper()}')
print(f'Nome com letras minúsculas: {nome.lower()}')
print(f'Nome completo tem {len(nome.replace(" ",""))} letras')
print(f'Primeiro nome tem {len(nome.split()[0])} letras')